<!DOCTYPE html>
<html lang = "en">
<head>
    <meta charset = "UTF-8">
    <title>Profile</title>
</head>
<body>
<h1>Profile page</h1>
<h2>Your data:</h2>
<form>
    <label for="login">Your login:</label>
    <output>${account.login}</output>
    <br>
    <label for="log">Your firstName:</label>
    <output>${account.firstName}</output>
    <br>
    <label for="log">Your lastName:</label>
    <output>${account.lastName}</output>
    <br>
</form>
</body>
</html>