<!DOCTYPE html>
<html lang = "en">
<head>
    <meta charset = "UTF-8">
    <title>Register</title>
</head>
<body>
<h1>SignUp Page</h1>
<h2>Please Enter your data:</h2>
<form action = "/signUp" method="post">
    <label for="login">Enter login:</label>
    <input id="login" name="login" placeholder="Your login">
    <br>
    <label for="password">Enter password:</label>
    <input type="password" id="password" name="password" placeholder="Your password">
    <input type="submit" value="SignUp">
</form>
</body>
</html>